### ISSUE TITLE
UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError

### ISSUE THREAD

**Issue by hoangvm** [calabash/calabash-ios-server#276] opened 2015-10-21 09:52 UTC
HI @jmoody

I have a bug that I want report you as below. Then please support me to resolve it. 
Thank you so much

REST_BETWEEN_SCENARIOS=1 DEVICE_ENDPOINT=http://10.48.0.36:37265 DEVICE_TARGET=dca1dc41e80d5fa49fc41133c03d704d2b62a06e BUNDLE_ID=test.core.app-cal APP_BUNDLE_PATH="app-cal.app" cucumber -v

Code:
 * features/support/env.rb
 * features/support/01_launch.rb
 * features/support/02_pre_stop_hooks.rb
 * features/step_definitions/calabash_steps.rb
 * features/step_definitions/my_first_steps.rb

Features:
 * features/my_first.feature
Parsing feature files took 0m0.016s

Feature: Running a test
 As an iOS developer
 I want to have a sample feature file
 So I can begin testing quickly

 Scenario: Example steps                            # features/my_first.feature:6
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
 Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError. 
  Logfile /var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151021-50207-1kzqybk/run_loop.out

2015-10-21 18:42:18.282 instruments[50319:333698] WebKit Threading Violation - initial use of WebKit from a secondary thread.
 
  (Calabash::Cucumber::Launcher::StartError)
 /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/launcher.rb:775:in `new_run_loop'
 /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/launcher.rb:636:in `relaunch'
 /Users/hoangvm/IOS-INP-Cal/calabash/features/support/01_launch.rb:27:in `Before'
   Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
   Then I swipe left                                # calabash-cucumber-0.15.0/features/step_definitions/calabash_steps.rb:222
   And I wait until I don't see "Please swipe left" # calabash-cucumber-0.15.0/features/step_definitions/calabash_steps.rb:158
   And take picture                                 # calabash-cucumber-0.15.0/features/step_definitions/calabash_steps.rb:217
     getaddrinfo: nodename nor servname provided, or not known (http://proxy-monolala.local:3128) (SocketError)
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `initialize'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `new'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `create_socket'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:747:in `block in connect'

/Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:612:in `query'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:164:in `query'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1191:in `do_get_block'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:725:in `post'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/http_helpers.rb:57:in `block in make_http_request'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/http_helpers.rb:50:in `times'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/http_helpers.rb:29:in `http'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
     /Users/hoangvm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/core.rb:877:in `calabash_exit'
     /Users/hoangvm/IOS-INP-Cal/calabash/features/support/01_launch.rb:34:in `After'

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
2m56.547s

*Here is my Environment*

# xcode-select --print-path
/Applications/Xcode.app/Contents/Developer/

# xcodebuild -version
Xcode 6.4
Build version 6E35b

# calabash-ios version
0.15.0

## I can run normally on Simulator iPhone6 6Plus then I can make sure no problem with -cal.app or BUNDLE PATH

**Comment by jmoody** [comment] 2015-10-21 13:34
> WebKit Threading Violation - initial use of WebKit from a secondary thread.

This output is normal.  Apple says it can be ignored - that is the official word.

The real problem is this:

```
UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
```

Looking at your command line arguments:

```
$ DEVICE_ENDPOINT=http://10.48.0.36:37265 \
DEVICE_TARGET=dca1dc41e80d5fa49fc41133c03d704d2b62a06e \ BUNDLE_ID=test.core.app-cal \
APP_BUNDLE_PATH="app-cal.app"
```

I see that you are conflating two concepts: targeting the simulator and targeting a physical device.

For physical devices, you must set these variables:

```
* DEVICE_ENDPOINT
* DEVICE_TARGET
* BUNDLE_ID
```

You should not set the `APP_BUNDLE_PATH` or `APP` variables.

You should go through the steps on the [Testing on Physical Devices](https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices) wiki page.

There is also this Hot Topic you should review: https://github.com/calabash/calabash-ios/wiki/Hot-Topics#7-errnoeintr-interrupted-system-call

For simulators, you set these variables:

```
* APP (or APP_BUNDLE_PATH)
* DEVICE_TARGET - this is optional if you want to target the default simulator.
```

> Xcode 6

Can you update to Xcode 7?

> Calabash 0.15.0

You should update to Calabash 0.16.4 (or the most recent version of Calabash).

With all that said, this is not the place for this issue, so I am going to close it for the following reasons:

1. I believe there are already Google Forum topics on this issue
2. There is a calabash-ios issue already: **Timed out waiting for UIAutomation run-loop** [#874](https://github.com/calabash/calabash-ios/issues/874) The reporter was able to solve his problem.

There is definitely a problem somewhere; many people are reporting similar issues.  I don't know what is causing the problems because I cannot reproduce.

**Closed by jmoody** 2015-10-21 13:34 UTC

**Comment by hoangvm** [comment] 2015-10-22 01:00
Thank you so much !
